Final Request for Alerts
Antonio32A/DungeonUtilities pull request #5
Opened 2020-10-02 15:06 UTC by misterdepth

Added MiniAlerts.

Also added "Stonk Dragon" to trivia.json as per request from bug reports.

2020-10-02 18:02 UTC, Antonio32A requested changes

2020-10-02 18:02 UTC, Antonio32A commented on features/miniAlert.js
> +            }],
remove the comma

2020-10-02 18:02 UTC, Antonio32A commented on features/miniAlert.js
> +class miniAlert {
should be called miniBossAlerts

2020-10-02 18:02 UTC, Antonio32A commented on features/miniAlert.js
> +        if (line.getName().includes('§cThe Cata') && line.getName().includes('mbs §8('));
double quotes

2020-10-02 19:56 UTC, ElOxo commented
Dont forget to Fix Deap Cavern to Deap Caverns in trivia.json

2020-10-23 06:40 UTC, Dolphin0xyz commented
You might need to add frozen adventurer to miniAlert.js

2020-11-16 22:59 UTC, closed without merging